spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
  context-path: /api
